language: python
services: docker

matrix:
  include:
    - arch: arm64-graviton2
      python: 3.8
      env: >
        DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
        PYTHON=cp36-cp36 PLAT=manylinux2014_aarch64
install:
  - python3 -m pip install twine
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -e PYTHON=$PYTHON -v `pwd`:/src $DOCKER_IMAGE /src/build-wheels.sh
  
after_success:
    - |
      if [ -n $TRAVIS_TAG ]; then
        python3 -m twine upload --skip-existing wheelhouse/*
      fi

